### ISSUE TITLE
Can we get both count and top_n?

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#3] opened 2023-05-08 17:28 UTC
Lucene returns a count (either estimated or exact) when collecting TOP_N hits ... but from the benchmark results UI it looks like Tantivy is always showing 1 hit.  Is this just a limitation of the benchmarker or does Tantivy really not report estimated hit count along with TOP_N?

**Comment by Tony-X** [comment] 2023-05-12 22:17
I dug deeper into the code and realized that tantivy currently can't do the efficient TOP docs collection with skipping together with a count. So to begin with we can have mode of getting TOP10 as well as the exact count. The TOP_10_COUNT command should do exactly that. I'll switch to that then figure out the skipping part later

**Comment by mikemccand** [comment] 2023-05-18 13:06
Hmm I don't think we want Tantivy to do two separate things (the TOP_N and the count)... that's not a fair comparison, since Lucene does both in a single query and produces either an estimation (lower bound on count) or a precise count.  So in the case where Tantivy does an exact count but Lucene did a lower bound (because it used skipping to collect the TOP_N), it's not fair to Tantivy.

Is it possible to turn off the BMW optimization in Tantivy?  We can turn it off in Lucene and then isolate out differences in BMW efficiency/implementation between the two.

**Comment by Tony-X** [comment] 2023-06-06 22:32
If we chain a TopDocs collector with Count collector, the query still runs one pass in tantivy and skipping is effectively disabled.

To some extent this is duplicate of https://github.com/Tony-X/search-benchmark-game/issues/30

**Closed as completed by Tony-X** 2023-06-06 22:32 UTC
