### ISSUE TITLE
Try turning off patching in Lucene's PFOR encoding

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#46] opened 2023-08-15 14:40 UTC
One difference between Lucene and Tantivy is Lucene uses the "patch" FOR, meaning the large values in a block are held out as exceptions so that the remaining values can use a smaller number of bits to encode, a tradeoff of CPU for lower storage space.

Let's try temporarily disabling the patching in Lucene, to match how Tantivy encodes, to see how much of a performance difference that is costing us?

**Comment by Tony-X** [comment] 2023-08-15 20:13
++ 

Is there an easy way to disable it? Based on my code-reading, it does not seem to be configurable

**Comment by slow-J** [comment] 2023-08-25 17:36
I forked a Test PostingsFormat, PostingsReader, PostingsWriter, codec and forutil to not do the patching for exceptions (large values). 

Done a quick test. Want to re-index and confirm again.
The performance difference for Lucene latency is: -2% in COUNT, -2% in TOP_10_COUNT, -2.07% in TOP_100.
It seems to be most improving Queries of `AndHighHigh` and `HighSloppyPhase`. `MedTerm` and `LowTerm` have regressions.

Done a benchmark (m6g.4xlarge) with COUNT, TOP_10_COUNT, TOP_100 against Lucene with pfor (from previous test after https://github.com/Tony-X/search-benchmark-game/commit/d1b928c941b369b625d3ba03df7bbdeb8cab97e5) and without the patching in the PFOR. See the test code here: https://github.com/slow-J/lucene/commit/cd689261f2094770ffb129d21bb81e6fcd40fbda (please let me know if there are any improvements I could have made). 

To run the code in the benchmark, I ran `gradlew jar` and copied the core jar to my benchmark workspace and added this to build.gradle: `implementation files("./libs/lucene-core-9.7.1-SNAPSHOT.jar")`. I added `config.setCodec(new LuceneTestCodec(LuceneTestCodec.Mode.BEST_COMPRESSION));` to BuildIndex.java.

Attaching results:
[results.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12441921/results.json.zip)

![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/248b02e9-8121-450d-94c0-0ba3e2615a9b)
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/d834605f-4817-426c-b713-f7e32c0c4ab9)
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/f2662f27-35ac-432b-8de1-57ce9561d0e9)

**Comment by Tony-X** [comment] 2023-09-06 21:32
Did you get a chance to check the index size impact?

**Comment by mikemccand** [comment] 2023-09-07 11:09
I also wonder whether removal of patching is more or less impactful on Graviton3?

**Comment by slow-J** [comment] 2023-09-07 12:07
Re-indexed again to make sure I have the right correct version built.

with patching turned on (baseline):
  10.098 GiB	idx

with patching turned off:
10.605 GiB    idx

So turning off patching causes a +5.0208% increase in the size of the index.

I'll test Graviton3 when I get a chance.

**Comment by slow-J** [comment] 2023-09-07 15:41
Variables
- Graviton3
- JDK 17
- Same test code as before

Candidate:
COUNT, avg: 11,108 μs
TOP_10_COUNT, avg: 18,652 μs
TOP_100, avg: 14,810 μs

Comparing to baseline results from https://github.com/Tony-X/search-benchmark-game/issues/36

Baseline:
COUNT, avg: 10,883 μs
TOP_10_COUNT, avg: 19,539 μs
TOP_100, avg: not tested

Changes with turning off the patching in PFOR encoding:
COUNT, avg: +2.06744% latency
TOP_10_COUNT, avg: -4.53964% latency


So the improvement to `TOP_10_COUNT` is doubled vs Graviton 2.
`COUNT` on the other hand has regressed.

Attaching results.json.
[results.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12551008/results.json.zip)

**Comment by mikemccand** [comment] 2023-09-12 10:14
> TOP_10_COUNT, avg: -4.53964% latency

This is quite a compelling gain.

Did you turn off patching for both `doc` and `freq`?  It's odd that `COUNT` regressed, but it is (should be!) only decoding `doc` in each postings list.

**Comment by slow-J** [comment] 2023-09-12 18:08
I turned off all patching in postings (both `doc` and `freq` I believe), see https://github.com/slow-J/lucene/commit/cd689261f2094770ffb129d21bb81e6fcd40fbda

I will re-run the graviton3 benchmark to double check will the `COUNT` regression stand.

**Comment by slow-J** [comment] 2023-09-18 13:53
Ran the Graviton 3 benchmark again.

COUNT, avg: 10,822 μs
TOP_10_COUNT, avg: 19,039 μs
TOP_100, avg: 14,914 μs

So this time compared to the control, we have
COUNT: -0.56%
TOP_10_COUNT:  -2.559%

So there is some variance between benchmark runs, and no `COUNT` regression this time.

**Comment by slow-J** [comment] 2023-11-06 19:33
The Lucene PR: https://github.com/apache/lucene/pull/12741 has been merged! Resolving!

**Closed as completed by slow-J** 2023-11-06 19:33 UTC
